# Generated by Django 5.2.3 on 2025-08-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resloved', 'Resolved'), ('Reopened', 'Reopened'), ('Closed', 'Closesd')], default='Open', max_length=20)),
                ('category', models.CharField(choices=[('POS Issue', 'POS Issue'), ('Transaction Issue', 'Transaction Issue'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
