# Generated by Django 5.2.3 on 2025-09-01 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(choices=[('Warri', 'Warri'), ('Lagos', 'Lagos'), ('Osun', 'Osun')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
